<?php

namespace DoctrineORMModule\Proxy\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StUser extends \Entity\StUser implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Entity\\StUser' . "\0" . 'id', '' . "\0" . 'Entity\\StUser' . "\0" . 'username', '' . "\0" . 'Entity\\StUser' . "\0" . 'displayName', '' . "\0" . 'Entity\\StUser' . "\0" . 'avatar', '' . "\0" . 'Entity\\StUser' . "\0" . 'password', '' . "\0" . 'Entity\\StUser' . "\0" . 'tokenChangePassword', '' . "\0" . 'Entity\\StUser' . "\0" . 'expiredChangePasswordTime', '' . "\0" . 'Entity\\StUser' . "\0" . 'email', '' . "\0" . 'Entity\\StUser' . "\0" . 'newEmail', '' . "\0" . 'Entity\\StUser' . "\0" . 'tokenChangeEmail', '' . "\0" . 'Entity\\StUser' . "\0" . 'expiredChangeEmailTime', '' . "\0" . 'Entity\\StUser' . "\0" . 'role', '' . "\0" . 'Entity\\StUser' . "\0" . 'status', '' . "\0" . 'Entity\\StUser' . "\0" . 'datetimeCreated');
        }

        return array('__isInitialized__', '' . "\0" . 'Entity\\StUser' . "\0" . 'id', '' . "\0" . 'Entity\\StUser' . "\0" . 'username', '' . "\0" . 'Entity\\StUser' . "\0" . 'displayName', '' . "\0" . 'Entity\\StUser' . "\0" . 'avatar', '' . "\0" . 'Entity\\StUser' . "\0" . 'password', '' . "\0" . 'Entity\\StUser' . "\0" . 'tokenChangePassword', '' . "\0" . 'Entity\\StUser' . "\0" . 'expiredChangePasswordTime', '' . "\0" . 'Entity\\StUser' . "\0" . 'email', '' . "\0" . 'Entity\\StUser' . "\0" . 'newEmail', '' . "\0" . 'Entity\\StUser' . "\0" . 'tokenChangeEmail', '' . "\0" . 'Entity\\StUser' . "\0" . 'expiredChangeEmailTime', '' . "\0" . 'Entity\\StUser' . "\0" . 'role', '' . "\0" . 'Entity\\StUser' . "\0" . 'status', '' . "\0" . 'Entity\\StUser' . "\0" . 'datetimeCreated');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (StUser $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayName($displayName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayName', array($displayName));

        return parent::setDisplayName($displayName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayName', array());

        return parent::getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatar($avatar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatar', array($avatar));

        return parent::setAvatar($avatar);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatar', array());

        return parent::getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setTokenChangePassword($tokenChangePassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTokenChangePassword', array($tokenChangePassword));

        return parent::setTokenChangePassword($tokenChangePassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getTokenChangePassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTokenChangePassword', array());

        return parent::getTokenChangePassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiredChangePasswordTime($expiredChangePasswordTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiredChangePasswordTime', array($expiredChangePasswordTime));

        return parent::setExpiredChangePasswordTime($expiredChangePasswordTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpiredChangePasswordTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpiredChangePasswordTime', array());

        return parent::getExpiredChangePasswordTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewEmail($newEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewEmail', array($newEmail));

        return parent::setNewEmail($newEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewEmail', array());

        return parent::getNewEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTokenChangeEmail($tokenChangeEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTokenChangeEmail', array($tokenChangeEmail));

        return parent::setTokenChangeEmail($tokenChangeEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getTokenChangeEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTokenChangeEmail', array());

        return parent::getTokenChangeEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiredChangeEmailTime($expiredChangeEmailTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiredChangeEmailTime', array($expiredChangeEmailTime));

        return parent::setExpiredChangeEmailTime($expiredChangeEmailTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpiredChangeEmailTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpiredChangeEmailTime', array());

        return parent::getExpiredChangeEmailTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', array($role));

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', array());

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatetimeCreated($datetimeCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatetimeCreated', array($datetimeCreated));

        return parent::setDatetimeCreated($datetimeCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatetimeCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatetimeCreated', array());

        return parent::getDatetimeCreated();
    }

}
