<?php echo $this->doctype()?>
<html lang="<?php echo $this->lang; ?>">
    <head>
        <?php echo $this->partial('partials/layout-admin/header')?>
    </head>
    <body>
        <div id="wrapper">
            <?php
                echo $this->partial('partials/layout-admin/navigation');
            ?>
            <div id="page-wrapper">
            <?php 
                echo $this->partial('partials/layout-admin/title');
                echo $this->content;
            ?>
            </div>
            <?php  echo $this->partial('partials/layout-admin/footer');?>
        </div>
        <?php echo $this->partial('partials/layout-admin/script')?>
	</body>
</html>
