<form class="form-signin" method="post" role="form" autocomplete="off">
    <h2 class="form-signin-heading"><?php echo $this->translate('please_sign_in', null, 'en')?></h2>
    <?php if(!empty($error)):?>
    <div class="alert alert-danger" role="alert">
      <strong>Oh Error!</strong> <?php echo $error ?>
    </div>
    <?php endif;?>
    <label for="login-username" class="sr-only">Email address</label>
    <input type="text" name="login_username" id="login-username" class="form-control" placeholder="Username" required autofocus>
    <label for="login-password" class="sr-only">Password</label>
    <input type="password" name="login_password" id="login-password" class="form-control" placeholder="Password" required>
    <div class="checkbox">
        <label>
          <input type="checkbox" value="1" name="rememberme"> Remember me
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
</form>