<?php
// Set title
$this->headtitle()
    ->setSeparator(' - ')
    ->setAutoEscape(false);
$this->headtitle($this->routeInfo()->title);
$this->headtitle('Admin');
$this->headtitle(_ST_SITE_NAME);
echo $this->headtitle() . PHP_EOL;

// Set Meta
$this->headmeta()->setCharset('utf-8');
$this->headmeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
$this->headmeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
echo $this->headmeta() . PHP_EOL;

// Set Link
$this->headLink(array(
    'rel' => 'shortcut icon',
    'type' => 'image/vnd.microsoft.icon',
    'href' => $this->serverUrl('/img/favicon.ico')
));

$this->headLink(array(
    'rel' => 'canonical',
    'href' => $this->serverUrl(true)
));

echo $this->headlink();

?>