<?php
$this->headScript()->appendFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array(
    'conditional' => 'lt IE 9'
));
// require js files
echo $this->headScript() . PHP_EOL;
?>
<script type="text/javascript">
var $app = {
		'module':'<?php echo $this->routeInfo()->module?>',
		'controller':'<?php echo $this->routeInfo()->controller ?>',
		'action':'<?php echo $this->routeInfo()->action ?>',
		'host':'<?php echo $this->serverurl("/")?>'
};
</script>
<script type="text/javascript" data-main="<?php echo "/js/" . $this->routeInfo()->module . "/main-backbone"?>" src="/js/require.js"></script>