<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                data-target=".navbar-collapse">
                <span class="icon-bar"></span> <span class="icon-bar"></span> <span
                    class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url($this->lang().'_home') ?>">
                <img class="pull-left" src="<?php echo $this->serverurl('/img/zf2-logo.png') ?>" alt="Zend Framework 2 Blank Project" />
                &nbsp;
                <?php echo $this->translate(_ST_SITE_NAME) ?>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <?php echo $this->stnavigation('Zend\Navigation\Default')->stmenu()->setUlClass('nav navbar-nav') ?>
            <ul class="nav navbar-nav navbar-right">
            <?php 
                $languages = $this->Utility()->getActiveLanguages();
                foreach ($languages as $lang):
            ?>
                <li>
                    <a href="<?php echo $this->utility()->getTranslateUrl($lang->getCode())?>" 
                        class="<?php echo $this->lang() == $lang->getCode() ? 'active' : '' ?>">
                        <img width="30" height="20" alt="" src="<?php echo $lang->getFlag()?>">
                    </a>
                </li>
            <?php endforeach;?>
            </ul>
        </div>
    </div>
</nav>