<?php

namespace Repository;

/**
 * CategoryDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
