<?php

namespace Repository;

/**
 * PageDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
