<?php

namespace Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends CommonRepository
{
    public function getBy($params)
    {
        $qb = $this->_em->createQueryBuilder();
        $detailClass = '\\'.$this->getEntityName()."Detail";
        $qb->select("o, d.name")->from($this->getEntityName(), 'o')
            ->join($detailClass, 'd', 'WITH', 'd.tag = o.id');
        $qb = $this->filter($qb, $params);
        $paginator = new Paginator($qb->getQuery(), false);
        return $paginator;
    }
}
