<?php

namespace Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends CommonRepository
{
    public function getBy($params)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select("o")->from($this->getEntityName(), 'o');
        $qb = $this->filter($qb, $params);
        $paginator = new Paginator($qb->getQuery(), false);
        return $paginator;
    }
}
